#!/usr/bin/env bash
# =============================================================================
# WordFix Production Deployment Script
# =============================================================================
# Usage:
#   chmod +x deploy.sh
#   ./deploy.sh              # Full deploy (build + start)
#   ./deploy.sh --rebuild    # Force rebuild all images
#   ./deploy.sh --reset-db   # Reset database (delete volume + fresh start)
#   ./deploy.sh --stop       # Stop all services
#   ./deploy.sh --logs       # View logs
#   ./deploy.sh --status     # Check status
# =============================================================================

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

COMPOSE_FILE="docker-compose.prod.yml"
ENV_FILE=".env.production"

log_info()  { echo -e "${BLUE}[INFO]${NC} $1"; }
log_ok()    { echo -e "${GREEN}[OK]${NC} $1"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# =============================================================================
# Auto-detect server IP
# =============================================================================
detect_server_ip() {
    local ip=""
    
    # Method 1: Get public IPv4 from external service (force IPv4 with -4)
    ip=$(curl -4 -sf --max-time 5 https://ifconfig.me 2>/dev/null || true)
    
    # Method 2: Get public IPv4 from another service
    if [ -z "$ip" ] || echo "$ip" | grep -q ':'; then
        ip=$(curl -4 -sf --max-time 5 https://api.ipify.org 2>/dev/null || true)
    fi
    
    # Method 3: Get public IPv4 from icanhazip
    if [ -z "$ip" ] || echo "$ip" | grep -q ':'; then
        ip=$(curl -4 -sf --max-time 5 https://icanhazip.com 2>/dev/null || true)
    fi
    
    # Method 4: Get IPv4 from hostname (filter out IPv6)
    if [ -z "$ip" ] || echo "$ip" | grep -q ':'; then
        ip=$(hostname -I 2>/dev/null | tr ' ' '\n' | grep -v ':' | head -1 || true)
    fi
    
    # Method 5: Get IPv4 from ip route
    if [ -z "$ip" ] || echo "$ip" | grep -q ':'; then
        ip=$(ip -4 route get 1.1.1.1 2>/dev/null | awk '{print $7; exit}' || true)
    fi
    
    # Validate: must be IPv4 (no colons)
    if [ -z "$ip" ] || echo "$ip" | grep -q ':'; then
        log_error "Could not detect IPv4 server IP. Please set SERVER_IP manually in $ENV_FILE"
        log_error "Example: Edit .env.production and set SERVER_IP=YOUR.SERVER.IP.HERE"
        exit 1
    fi
    
    echo "$ip"
}

# =============================================================================
# Generate .env.production if not exists or update SERVER_IP
# =============================================================================
setup_env() {
    local server_ip="$1"
    
    if [ ! -f "$ENV_FILE" ]; then
        log_info "Creating $ENV_FILE with detected IP: $server_ip"
        
        # Generate a random secret key
        local secret_key
        secret_key=$(openssl rand -hex 32 2>/dev/null || python3 -c "import secrets; print(secrets.token_hex(32))" 2>/dev/null || echo "change-this-to-a-random-string-$(date +%s)")
        
        cat > "$ENV_FILE" << EOF
# =============================================================================
# WordFix Production Environment — Auto-generated by deploy.sh
# Generated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
# =============================================================================

# Server
SERVER_IP=${server_ip}

# Django
SECRET_KEY=${secret_key}
DEBUG=False
DJANGO_SETTINGS_MODULE=config.settings.production
ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0,${server_ip}

# Database
POSTGRES_DB=wordfix
POSTGRES_USER=wordfix_user
POSTGRES_PASSWORD=wordfix_pass
POSTGRES_HOST=db
POSTGRES_PORT=5432

# Redis
REDIS_URL=redis://redis:6379/0

# Celery
CELERY_BROKER_URL=redis://redis:6379/1
CELERY_RESULT_BACKEND=redis://redis:6379/2

# CORS
CORS_ALLOWED_ORIGINS=http://${server_ip},http://localhost,http://127.0.0.1

# SSL (set to True when you add HTTPS)
USE_SSL=False

# AI Provider (gemini | groq | openai)
AI_PROVIDER=groq
GEMINI_API_KEY=
GEMINI_MODEL=gemini-2.0-flash
GROQ_API_KEY=
GROQ_MODEL=llama-3.3-70b-versatile
OPENAI_API_KEY=
OPENAI_MODEL=gpt-4o-mini
AI_MAX_RETRIES=3
AI_TIMEOUT=30
WORD_ENRICHMENT_ENABLED=True

# Google OAuth (optional)
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=

# Frontend Build
VITE_API_URL=/api/v1
VITE_APP_NAME=WordFix
VITE_APP_VERSION=1.0.0
EOF
        
        log_ok "$ENV_FILE created successfully"
        log_warn "IMPORTANT: Edit $ENV_FILE to set your API keys (GROQ_API_KEY, etc.)"
    else
        # Update SERVER_IP in existing .env.production
        log_info "Updating SERVER_IP in existing $ENV_FILE to: $server_ip"
        
        # Update SERVER_IP
        if grep -q "^SERVER_IP=" "$ENV_FILE"; then
            sed -i "s|^SERVER_IP=.*|SERVER_IP=${server_ip}|" "$ENV_FILE"
        fi
        
        # Update ALLOWED_HOSTS to include server IP
        if grep -q "^ALLOWED_HOSTS=" "$ENV_FILE"; then
            if ! grep "ALLOWED_HOSTS=" "$ENV_FILE" | grep -q "$server_ip"; then
                sed -i "s|^ALLOWED_HOSTS=\(.*\)|ALLOWED_HOSTS=\1,${server_ip}|" "$ENV_FILE"
            fi
        fi
        
        # Update CORS_ALLOWED_ORIGINS to include server IP
        if grep -q "^CORS_ALLOWED_ORIGINS=" "$ENV_FILE"; then
            if ! grep "CORS_ALLOWED_ORIGINS=" "$ENV_FILE" | grep -q "$server_ip"; then
                sed -i "s|^CORS_ALLOWED_ORIGINS=\(.*\)|CORS_ALLOWED_ORIGINS=\1,http://${server_ip}|" "$ENV_FILE"
            fi
        fi
        
        log_ok "$ENV_FILE updated"
    fi
}

# =============================================================================
# Check prerequisites
# =============================================================================
check_prerequisites() {
    log_info "Checking prerequisites..."
    
    if ! command -v docker &> /dev/null; then
        log_error "Docker is not installed. Install it: https://docs.docker.com/engine/install/ubuntu/"
        exit 1
    fi
    
    if ! docker compose version &> /dev/null; then
        log_error "Docker Compose V2 is not installed."
        exit 1
    fi
    
    if ! docker info &> /dev/null 2>&1; then
        log_error "Docker daemon is not running or current user has no access."
        log_info "Try: sudo usermod -aG docker \$USER && newgrp docker"
        exit 1
    fi
    
    log_ok "All prerequisites met"
}

# =============================================================================
# Deploy
# =============================================================================
deploy() {
    local rebuild="${1:-false}"
    
    log_info "=========================================="
    log_info "  WordFix Production Deployment"
    log_info "=========================================="
    
    check_prerequisites
    
    # Detect server IP
    log_info "Detecting server IP..."
    local server_ip
    server_ip=$(detect_server_ip)
    log_ok "Server IP: $server_ip"
    
    # Setup environment
    setup_env "$server_ip"
    
    # Ensure nginx config directory exists
    mkdir -p nginx
    
    # Check for potential DB password mismatch with existing volume
    if docker volume ls -q 2>/dev/null | grep -q "wordfix_postgres_data"; then
        log_warn "Existing postgres_data volume detected."
        log_warn "If you changed POSTGRES_PASSWORD, the old volume still has the old password."
        log_warn "Run './deploy.sh --reset-db' to delete volumes and start fresh if needed."
    fi
    
    # Build and start
    if [ "$rebuild" = "true" ]; then
        log_info "Rebuilding all images..."
        docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" build --no-cache
    fi
    
    log_info "Starting services..."
    docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" up -d --build
    
    # Wait for services to be healthy
    log_info "Waiting for services to be healthy..."
    local max_wait=120
    local waited=0
    while [ $waited -lt $max_wait ]; do
        if docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" ps | grep -q "healthy"; then
            break
        fi
        sleep 5
        waited=$((waited + 5))
        echo -n "."
    done
    echo ""
    
    # Show status
    log_info ""
    docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" ps
    
    log_info ""
    log_ok "=========================================="
    log_ok "  Deployment complete!"
    log_ok "=========================================="
    log_ok ""
    log_ok "  Frontend:  http://${server_ip}"
    log_ok "  API:       http://${server_ip}/api/v1/"
    log_ok "  API Docs:  http://${server_ip}/api/v1/schema/swagger/"
    log_ok "  Admin:     http://${server_ip}/admin/"
    log_ok "  Health:    http://${server_ip}/api/v1/health/"
    log_ok ""
    log_info "Commands:"
    log_info "  ./deploy.sh --logs     View logs"
    log_info "  ./deploy.sh --stop     Stop all services"
    log_info "  ./deploy.sh --status   Check status"
    log_info "  ./deploy.sh --rebuild  Force rebuild"
}

# =============================================================================
# CLI Commands
# =============================================================================
case "${1:-}" in
    --stop)
        log_info "Stopping all services..."
        docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" down
        log_ok "All services stopped"
        ;;
    --reset-db)
        log_warn "This will DELETE all database data and start fresh!"
        read -p "Are you sure? (y/N): " confirm
        if [ "$confirm" = "y" ] || [ "$confirm" = "Y" ]; then
            log_info "Stopping services and removing database volume..."
            docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" down -v 2>/dev/null || true
            log_ok "Volumes removed. Starting fresh deployment..."
            deploy "true"
        else
            log_info "Cancelled."
        fi
        ;;
    --logs)
        docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" logs -f --tail=100
        ;;
    --status)
        docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" ps
        echo ""
        log_info "Health check:"
        local_ip=$(grep "^SERVER_IP=" "$ENV_FILE" 2>/dev/null | cut -d '=' -f2 || echo "localhost")
        curl -sf "http://localhost:80/api/v1/health/" 2>/dev/null && log_ok "API is healthy" || log_warn "API may not be ready yet"
        ;;
    --rebuild)
        deploy "true"
        ;;
    --help|-h)
        echo "WordFix Production Deployment"
        echo ""
        echo "Usage: ./deploy.sh [OPTION]"
        echo ""
        echo "Options:"
        echo "  (none)       Full deploy (build + start)"
        echo "  --rebuild    Force rebuild all images"
        echo "  --reset-db   Delete database volume and start fresh"
        echo "  --stop       Stop all services"
        echo "  --logs       View logs (follow mode)"
        echo "  --status     Check service status"
        echo "  --help       Show this help"
        ;;
    *)
        deploy "false"
        ;;
esac
