apiVersion: v1
kind: Secret
metadata:
  name: ai-secrets
  namespace: wordfix
  labels:
    app.kubernetes.io/part-of: wordfix
    app.kubernetes.io/component: config
type: Opaque
stringData:
  GEMINI_API_KEY: ""
  GROQ_API_KEY: ""
  OPENAI_API_KEY: ""
