apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: wordfix
  labels:
    app.kubernetes.io/part-of: wordfix
    app.kubernetes.io/component: config
type: Opaque
stringData:
  SECRET_KEY: "django-insecure-change-me-in-production"
  GOOGLE_CLIENT_ID: ""
  GOOGLE_CLIENT_SECRET: ""
  CORS_ALLOWED_ORIGINS: "http://localhost:30080"
