apiVersion: v1
kind: Secret
metadata:
  name: auth-db-secrets
  namespace: wordfix
  labels:
    app.kubernetes.io/part-of: wordfix
    app.kubernetes.io/component: database
type: Opaque
stringData:
  POSTGRES_DB: "wordfix_auth"
  POSTGRES_USER: "auth_user"
  POSTGRES_PASSWORD: "auth_pass"
  DATABASE_URL: "postgresql+asyncpg://auth_user:auth_pass@auth-db:5432/wordfix_auth"
