apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: wordfix
  labels:
    app.kubernetes.io/part-of: wordfix
    app.kubernetes.io/component: database
type: Opaque
stringData:
  POSTGRES_DB: "wordfix"
  POSTGRES_USER: "wordfix_user"
  POSTGRES_PASSWORD: "wordfix_pass"
