apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secrets
  namespace: wordfix
  labels:
    app.kubernetes.io/part-of: wordfix
    app.kubernetes.io/component: queue
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: "wordfix"
  RABBITMQ_DEFAULT_PASS: "wordfix_mq"
  RABBITMQ_URL: "amqp://wordfix:wordfix_mq@rabbitmq:5672/"
