// ─── API Endpoints ─────────────────────────────────────────────────────────────

const API_ENDPOINTS = {
  AUTH: {
    REGISTER: '/auth/register/',
    LOGIN: '/auth/login/',
    LOGOUT: '/auth/logout/',
    REFRESH: '/auth/token/refresh/',
    PROFILE: '/auth/profile/',
    CHANGE_PASSWORD: '/auth/change-password/',
    GOOGLE_LOGIN: '/auth/google/',
    PROVIDERS: '/auth/providers/',
  },
  ONBOARDING: {
    QUESTIONS: '/auth/onboarding/questions/',
    SUBMIT: '/auth/onboarding/submit/',
    SKIP: '/auth/onboarding/skip/',
    STATUS: '/auth/onboarding/status/',
  },
  WORDS: {
    LIST: '/words/',
    DETAIL: (id: string) => `/words/${id}/`,
    BULK: '/words/bulk/',
    STATS: '/words/stats/',
    REVIEW: '/words/review/',
    CATEGORIES: '/words/categories/',
    CATEGORY_DETAIL: (id: string) => `/words/categories/${id}/`,
    ENRICH: (id: string) => `/words/${id}/enrich/`,
    ENRICHMENT_STATUS: (id: string) => `/words/${id}/enrichment-status/`,
  },
  REVIEW: {
    WORDS: '/review/words/',
    SESSIONS: '/review/sessions/',
    SESSION_DETAIL: (id: string) => `/review/sessions/${id}/`,
    SESSION_SUBMIT: (id: string) => `/review/sessions/${id}/answer/`,
    SESSION_COMPLETE: (id: string) => `/review/sessions/${id}/complete/`,
    SUMMARY: '/review/summary/',
    STREAK: '/review/streak/',
    DAILY_PROGRESS: '/review/daily-progress/',
  },
  TESTS: {
    GENERATE: '/tests/generate/',
    HISTORY: '/tests/history/',
    DETAIL: (id: string) => `/tests/${id}/`,
    ANSWER: (id: string) => `/tests/${id}/answer/`,
    COMPLETE: (id: string) => `/tests/${id}/complete/`,
  },
  GAMES: {
    SPEED_ROUND_START: '/games/speed-round/start/',
    SPEED_ROUND_SUBMIT: '/games/speed-round/submit/',
    WORD_MATCH_START: '/games/word-match/start/',
    WORD_MATCH_SUBMIT: '/games/word-match/submit/',
    WORD_CONTEXT_START: '/games/word-context/start/',
    WORD_CONTEXT_SUBMIT: '/games/word-context/submit/',
    STORY_BUILDER_START: '/games/story-builder/start/',
    STORY_BUILDER_SUBMIT: '/games/story-builder/submit/',
    STORY_BUILDER_COMPLETE: '/games/story-builder/complete/',
    LISTENING_START: '/games/listening/start/',
    LISTENING_ANSWER: '/games/listening/answer/',
    LISTENING_COMPLETE: '/games/listening/complete/',
    HISTORY: '/games/history/',
    STATS: '/games/stats/',
  },
  PROGRESS: {
    USER_PROGRESS: '/users/progress/',
    XP_HISTORY: '/users/xp-history/',
    USER_BADGES: '/users/badges/',
    ALL_BADGES: '/badges/',
  },
  NOTIFICATIONS: {
    LIST: '/notifications/',
    MARK_READ: '/notifications/read/',
    UNREAD_COUNT: '/notifications/unread-count/',
  },
  IMPORT: {
    ANALYZE: '/words/import/analyze/',
    ADD: '/words/import/add/',
    CSV_VALIDATE: '/words/import/csv/validate/',
    CSV_IMPORT: '/words/import/csv/',
  },
  CHAT: {
    START: '/chat/start/',
    HISTORY: '/chat/history/',
    SESSION_DETAIL: (id: string) => `/chat/sessions/${id}/`,
    SEND_MESSAGE: (id: string) => `/chat/sessions/${id}/message/`,
    END: (id: string) => `/chat/sessions/${id}/end/`,
  },
  ANALYTICS: {
    OVERVIEW: '/analytics/overview/',
    WEEKLY: '/analytics/weekly/',
    MONTHLY: '/analytics/monthly/',
    DIFFICULT_WORDS: '/analytics/difficult-words/',
    WORD_PROGRESS: '/analytics/word-progress/',
    CALENDAR: '/analytics/calendar/',
  },
  CONFUSING_PAIRS: {
    LIST: '/words/confusing-pairs/',
    DETAIL: (id: string) => `/words/confusing-pairs/${id}/`,
    DRILL: (id: string) => `/words/confusing-pairs/${id}/drill/`,
    RESOLVE: (id: string) => `/words/confusing-pairs/${id}/resolve/`,
    COUNT: '/words/confusing-pairs/count/',
  },
  CHALLENGES: {
    TODAY: '/challenges/today/',
    CLAIM: '/challenges/claim/',
  },
  SYSTEM: {
    HEALTH: '/system/health/detailed/',
    CONFIG: '/system/config/status/',
  },
  LEARNING: {
    PROFILE: '/learning-profile/',
    ANALYZE: '/learning-profile/analyze/',
    MISTAKES: '/learning-profile/mistake-patterns/',
    RECOMMENDATIONS: '/learning-profile/recommendations/',
    DOMAIN_COVERAGE: '/learning-profile/domain-coverage/',
    DIFFICULTY: '/learning-profile/difficulty/',
  },
} as const;

export default API_ENDPOINTS;
