from .word_views import *
from .review_views import *
from .test_views import *
from .game_views import *
from .enrichment_views import *
from .import_views import *
from .chat_views import *
from .analytics_views import *
from .confusing_views import *
from .challenge_views import *
