apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: wordfix
  labels:
    app.kubernetes.io/part-of: wordfix
    app.kubernetes.io/component: backend
data:
  JWT_ALGORITHM: "HS256"
  JWT_ACCESS_LIFETIME_MINUTES: "60"
  JWT_REFRESH_LIFETIME_DAYS: "7"
  REDIS_URL: "redis://redis:6379/3"
  GRPC_PORT: "50051"
  HTTP_PORT: "8001"
  DEBUG: "False"
