apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  namespace: wordfix
  labels:
    app.kubernetes.io/part-of: wordfix
    app.kubernetes.io/component: backend
data:
  DJANGO_SETTINGS_MODULE: "config.settings.production"
  DEBUG: "False"
  ALLOWED_HOSTS: "localhost,127.0.0.1,0.0.0.0"
  POSTGRES_HOST: "db"
  POSTGRES_PORT: "5432"
  REDIS_URL: "redis://redis:6379/0"
  CELERY_BROKER_URL: "redis://redis:6379/1"
  CELERY_RESULT_BACKEND: "redis://redis:6379/2"
  AI_PROVIDER: "groq"
  GEMINI_MODEL: "gemini-2.0-flash"
  GROQ_MODEL: "llama-3.3-70b-versatile"
  OPENAI_MODEL: "gpt-4o-mini"
