apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: wordfix
  labels:
    app.kubernetes.io/part-of: wordfix
    app.kubernetes.io/component: cache
data:
  redis.conf: |
    appendonly yes
    maxmemory 256mb
    maxmemory-policy allkeys-lru
