# Generated by Django 5.2.11 on 2026-04-16 01:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImmersiveScenario",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("name", models.CharField(max_length=100)),
                ("name_uz", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("description_uz", models.TextField()),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("office", "Office"),
                            ("restaurant", "Restaurant"),
                            ("airport", "Airport"),
                            ("hospital", "Hospital"),
                            ("school", "School"),
                            ("hotel", "Hotel"),
                            ("shop", "Shop"),
                            ("bank", "Bank"),
                            ("park", "Park"),
                            ("gym", "Gym"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("A1", "Beginner"),
                            ("A2", "Elementary"),
                            ("B1", "Intermediate"),
                            ("B2", "Upper Intermediate"),
                            ("C1", "Advanced"),
                            ("C2", "Proficient"),
                        ],
                        max_length=2,
                    ),
                ),
                ("scene_config", models.JSONField(default=dict)),
                ("target_vocabulary", models.JSONField(default=list)),
                ("expected_phrases", models.JSONField(default=list)),
                ("max_turns", models.PositiveIntegerField(default=8)),
                ("time_limit_seconds", models.PositiveIntegerField(default=600)),
                ("xp_reward", models.PositiveIntegerField(default=50)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Immersive Scenario",
                "verbose_name_plural": "Immersive Scenarios",
                "db_table": "immersive_scenarios",
                "ordering": ["order", "difficulty"],
            },
        ),
        migrations.CreateModel(
            name="NPCCharacter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("name", models.CharField(max_length=50)),
                ("role", models.CharField(max_length=100)),
                ("role_uz", models.CharField(max_length=100)),
                ("personality", models.TextField()),
                ("avatar_config", models.JSONField(default=dict)),
                ("initial_greeting", models.TextField()),
                ("system_prompt", models.TextField()),
                ("voice_config", models.JSONField(default=dict)),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="npcs",
                        to="immersive.immersivescenario",
                    ),
                ),
            ],
            options={
                "verbose_name": "NPC Character",
                "verbose_name_plural": "NPC Characters",
                "db_table": "npc_characters",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ImmersiveSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                            ("timeout", "Timeout"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "input_mode",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("voice", "Voice"),
                            ("mixed", "Mixed"),
                        ],
                        default="text",
                        max_length=5,
                    ),
                ),
                ("score", models.PositiveIntegerField(default=0)),
                ("max_score", models.PositiveIntegerField(default=100)),
                ("turn_count", models.PositiveIntegerField(default=0)),
                ("hints_used", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                ("xp_earned", models.PositiveIntegerField(default=0)),
                ("fluency_score", models.FloatField(default=0.0)),
                ("accuracy_score", models.FloatField(default=0.0)),
                ("vocabulary_score", models.FloatField(default=0.0)),
                ("task_completion_score", models.FloatField(default=0.0)),
                ("conversation_context", models.JSONField(default=list)),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="immersive.immersivescenario",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="immersive_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "npc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="immersive.npccharacter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Immersive Session",
                "verbose_name_plural": "Immersive Sessions",
                "db_table": "immersive_sessions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ConversationTurn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("turn_number", models.PositiveIntegerField()),
                (
                    "role",
                    models.CharField(
                        choices=[("npc", "NPC"), ("user", "User")], max_length=4,
                    ),
                ),
                ("content", models.TextField()),
                ("audio_url", models.CharField(blank=True, default="", max_length=500)),
                (
                    "input_type",
                    models.CharField(
                        choices=[("text", "Text"), ("voice", "Voice")],
                        default="text",
                        max_length=5,
                    ),
                ),
                ("grammar_errors", models.JSONField(default=list)),
                ("vocabulary_feedback", models.JSONField(default=list)),
                ("relevance_score", models.FloatField(default=0.0)),
                ("grammar_score", models.FloatField(default=0.0)),
                ("vocabulary_score_turn", models.FloatField(default=0.0)),
                ("score", models.PositiveIntegerField(default=0)),
                ("hint_level_used", models.PositiveIntegerField(default=0)),
                (
                    "response_time_ms",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turns",
                        to="immersive.immersivesession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversation Turn",
                "verbose_name_plural": "Conversation Turns",
                "db_table": "conversation_turns",
                "ordering": ["turn_number"],
                "unique_together": {("session", "turn_number")},
            },
        ),
    ]
