from .common_deps import *
from .word_deps import *
from .enrichment_deps import *
from .review_deps import *
from .test_deps import *
from .game_deps import *
from .import_deps import *
from .chat_deps import *
from .analytics_deps import *
from .confusing_deps import *
from .challenge_deps import *
from .distractor_deps import *
