# Generated by Django 5.2.11 on 2026-02-08 16:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=255)),
                ("icon", models.CharField(default="award", max_length=50)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("words", "Words"),
                            ("streak", "Streak"),
                            ("review", "Review"),
                            ("test", "Test"),
                            ("game", "Game"),
                            ("mastery", "Mastery"),
                            ("level", "Level"),
                        ],
                        max_length=10,
                    ),
                ),
                ("xp_reward", models.PositiveIntegerField(default=0)),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("common", "Common"),
                            ("rare", "Rare"),
                            ("epic", "Epic"),
                            ("legendary", "Legendary"),
                        ],
                        default="common",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Badge",
                "verbose_name_plural": "Badges",
                "db_table": "badges",
                "ordering": ["category", "code"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("review_reminder", "Review Reminder"),
                            ("streak_warning", "Streak Warning"),
                            ("badge_earned", "Badge Earned"),
                            ("level_up", "Level Up"),
                            ("daily_goal_complete", "Daily Goal Complete"),
                            ("word_mastered", "Word Mastered"),
                            ("weekly_report", "Weekly Report"),
                        ],
                        max_length=25,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_xp", models.PositiveIntegerField(default=0)),
                ("level", models.PositiveIntegerField(default=1)),
                ("words_learned_total", models.PositiveIntegerField(default=0)),
                ("words_mastered_total", models.PositiveIntegerField(default=0)),
                ("tests_completed", models.PositiveIntegerField(default=0)),
                ("games_played", models.PositiveIntegerField(default=0)),
                ("reviews_completed", models.PositiveIntegerField(default=0)),
                ("perfect_scores", models.PositiveIntegerField(default=0)),
                ("total_study_time_seconds", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Progress",
                "verbose_name_plural": "User Progress",
                "db_table": "user_progress",
            },
        ),
        migrations.CreateModel(
            name="XPTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.IntegerField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("word_added", "Word Added"),
                            ("review_correct", "Review Correct"),
                            ("review_incorrect", "Review Incorrect"),
                            ("review_complete", "Review Session Complete"),
                            ("review_perfect", "Perfect Review"),
                            ("test_complete", "Test Complete"),
                            ("test_good", "Test Good Score"),
                            ("test_perfect", "Perfect Test"),
                            ("game_complete", "Game Complete"),
                            ("game_good", "Game Good Score"),
                            ("word_mastered", "Word Mastered"),
                            ("streak_7", "7-Day Streak"),
                            ("streak_30", "30-Day Streak"),
                            ("daily_goal", "Daily Goal Complete"),
                            ("badge_reward", "Badge Reward"),
                            ("level_up", "Level Up"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="xp_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "XP Transaction",
                "verbose_name_plural": "XP Transactions",
                "db_table": "xp_transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_badges",
                        to="users.badge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Badge",
                "verbose_name_plural": "User Badges",
                "db_table": "user_badges",
                "ordering": ["-earned_at"],
                "unique_together": {("user", "badge")},
            },
        ),
    ]
