# Generated by Django 5.2.11 on 2026-02-11 18:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_badge_notification_userprogress_xptransaction_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnboardingQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("A1", "A1"),
                            ("A2", "A2"),
                            ("B1", "B1"),
                            ("B2", "B2"),
                            ("C1", "C1"),
                            ("C2", "C2"),
                        ],
                        max_length=2,
                    ),
                ),
                ("question_text", models.TextField()),
                ("correct_answer", models.CharField(max_length=200)),
                ("options", models.JSONField(default=list)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Onboarding Question",
                "verbose_name_plural": "Onboarding Questions",
                "db_table": "onboarding_questions",
                "ordering": ["level", "order"],
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="has_completed_onboarding",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="OnboardingResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("answers", models.JSONField(default=list)),
                ("determined_level", models.CharField(default="A1", max_length=2)),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                ("total_correct", models.PositiveIntegerField(default=0)),
                ("total_questions", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_result",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Onboarding Result",
                "verbose_name_plural": "Onboarding Results",
                "db_table": "onboarding_results",
            },
        ),
    ]
