# Generated by Django 5.2.11 on 2026-02-13 16:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_onboardingquestion_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "preferred_style",
                    models.CharField(
                        choices=[
                            ("visual", "Visual"),
                            ("auditory", "Auditory"),
                            ("reading", "Reading"),
                            ("kinesthetic", "Kinesthetic"),
                        ],
                        default="visual",
                        max_length=15,
                    ),
                ),
                ("style_confidence", models.FloatField(default=0.0)),
                ("best_hour_start", models.PositiveIntegerField(default=9)),
                ("best_hour_end", models.PositiveIntegerField(default=12)),
                ("best_days", models.JSONField(blank=True, default=list)),
                ("avg_session_duration", models.PositiveIntegerField(default=15)),
                ("optimal_words_per_session", models.PositiveIntegerField(default=10)),
                ("avg_retention_rate", models.FloatField(default=0.0)),
                ("strongest_skills", models.JSONField(blank=True, default=list)),
                ("weakest_skills", models.JSONField(blank=True, default=list)),
                ("current_difficulty_level", models.FloatField(default=0.5)),
                ("difficulty_adjustment_rate", models.FloatField(default=0.05)),
                ("last_analyzed_at", models.DateTimeField(blank=True, null=True)),
                ("analysis_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Learning Profile",
                "verbose_name_plural": "Learning Profiles",
                "db_table": "learning_profiles",
            },
        ),
        migrations.CreateModel(
            name="WordRecommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("recommended_word", models.CharField(max_length=100)),
                (
                    "translation",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "reason_type",
                    models.CharField(
                        choices=[
                            ("domain_gap", "Domain Gap"),
                            ("confusion_fix", "Confusion Fix"),
                            ("level_appropriate", "Level Appropriate"),
                            ("high_frequency", "High Frequency"),
                            ("user_interest", "User Interest"),
                        ],
                        default="level_appropriate",
                        max_length=20,
                    ),
                ),
                ("priority_score", models.FloatField(default=0.5)),
                ("is_accepted", models.BooleanField(default=False)),
                ("is_dismissed", models.BooleanField(default=False)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("ai_confidence", models.FloatField(default=0.0)),
                ("source_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="word_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Word Recommendation",
                "verbose_name_plural": "Word Recommendations",
                "db_table": "word_recommendations",
                "ordering": ["-priority_score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DomainCoverage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("academic", "Academic"),
                            ("business", "Business"),
                            ("technology", "Technology"),
                            ("daily_life", "Daily Life"),
                            ("science", "Science"),
                            ("arts", "Arts"),
                            ("travel", "Travel"),
                            ("medical", "Medical"),
                            ("legal", "Legal"),
                            ("social", "Social"),
                        ],
                        max_length=15,
                    ),
                ),
                ("total_words_in_domain", models.PositiveIntegerField(default=0)),
                ("coverage_percentage", models.FloatField(default=0.0)),
                ("mastered_count", models.PositiveIntegerField(default=0)),
                ("learning_count", models.PositiveIntegerField(default=0)),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domain_coverages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Domain Coverage",
                "verbose_name_plural": "Domain Coverages",
                "db_table": "domain_coverages",
                "unique_together": {("user", "domain")},
            },
        ),
        migrations.CreateModel(
            name="MistakePattern",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pattern_type",
                    models.CharField(
                        choices=[
                            ("l1_interference", "L1 Interference"),
                            ("morphological", "Morphological"),
                            ("semantic", "Semantic"),
                            ("phonological", "Phonological"),
                            ("spelling", "Spelling"),
                            ("collocation", "Collocation"),
                            ("grammar", "Grammar"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("examples", models.JSONField(blank=True, default=list)),
                ("occurrence_count", models.PositiveIntegerField(default=1)),
                ("last_occurred_at", models.DateTimeField(auto_now=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("drills_completed", models.PositiveIntegerField(default=0)),
                ("success_rate_after_drills", models.FloatField(default=0.0)),
                ("related_words", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mistake_patterns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mistake Pattern",
                "verbose_name_plural": "Mistake Patterns",
                "db_table": "mistake_patterns",
                "ordering": ["-occurrence_count"],
                "indexes": [
                    models.Index(
                        fields=["user", "pattern_type"],
                        name="mistake_pat_user_id_823837_idx",
                    ),
                    models.Index(
                        fields=["user", "is_resolved"],
                        name="mistake_pat_user_id_598db9_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SessionPerformance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("review", "Review"),
                            ("test", "Test"),
                            ("game", "Game"),
                            ("chat", "Chat"),
                        ],
                        max_length=10,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField()),
                ("hour_of_day", models.PositiveIntegerField(default=0)),
                ("day_of_week", models.PositiveIntegerField(default=0)),
                ("accuracy", models.FloatField(default=0.0)),
                ("completion_rate", models.FloatField(default=0.0)),
                ("engagement_score", models.FloatField(default=0.0)),
                ("effectiveness_score", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_performances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Session Performance",
                "verbose_name_plural": "Session Performances",
                "db_table": "session_performances",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "hour_of_day"],
                        name="session_per_user_id_17712a_idx",
                    ),
                    models.Index(
                        fields=["user", "day_of_week"],
                        name="session_per_user_id_5425d4_idx",
                    ),
                ],
            },
        ),
    ]
