# Generated by Django 5.2.11 on 2026-02-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_learningprofile_wordrecommendation_domaincoverage_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="wordrecommendation",
            index=models.Index(
                fields=["user", "recommended_word"],
                name="word_recomm_user_id_e04441_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="wordrecommendation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_accepted", False), ("is_dismissed", False)),
                fields=("user", "recommended_word"),
                name="unique_active_recommendation_per_user",
            ),
        ),
    ]
