# Generated by Django 5.2.11 on 2026-02-06 20:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WordCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "color",
                    models.CharField(
                        default="#6C5CE7",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Color must be a valid hex color code (e.g., #6C5CE7).",
                                regex="^#[0-9A-Fa-f]{6}$",
                            )
                        ],
                    ),
                ),
                ("icon", models.CharField(default="book", max_length=50)),
                ("words_count", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="word_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Word Category",
                "verbose_name_plural": "Word Categories",
                "db_table": "word_categories",
                "ordering": ["name"],
                "unique_together": {("user", "name")},
            },
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("original_word", models.CharField(db_index=True, max_length=100)),
                (
                    "translation",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "pronunciation",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "part_of_speech",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("noun", "Noun"),
                            ("verb", "Verb"),
                            ("adjective", "Adjective"),
                            ("adverb", "Adverb"),
                            ("preposition", "Preposition"),
                            ("conjunction", "Conjunction"),
                            ("pronoun", "Pronoun"),
                            ("interjection", "Interjection"),
                            ("phrase", "Phrase"),
                            ("other", "Other"),
                        ],
                        default="",
                        max_length=15,
                    ),
                ),
                ("definition", models.TextField(blank=True, default="")),
                ("example_sentence", models.TextField(blank=True, default="")),
                ("example_translation", models.TextField(blank=True, default="")),
                ("synonyms", models.JSONField(blank=True, default=list)),
                ("antonyms", models.JSONField(blank=True, default=list)),
                ("collocations", models.JSONField(blank=True, default=list)),
                ("word_family", models.JSONField(blank=True, default=list)),
                ("image_url", models.URLField(blank=True, default="")),
                ("audio_url", models.URLField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=6,
                    ),
                ),
                ("is_enriched", models.BooleanField(default=False)),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("next_review_at", models.DateTimeField(blank=True, null=True)),
                ("review_count", models.PositiveIntegerField(default=0)),
                ("correct_count", models.PositiveIntegerField(default=0)),
                ("incorrect_count", models.PositiveIntegerField(default=0)),
                ("last_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("is_mastered", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="words",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="words",
                        to="words.wordcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Word",
                "verbose_name_plural": "Words",
                "db_table": "words",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_mastered"], name="words_user_id_1952c9_idx"
                    ),
                    models.Index(
                        fields=["user", "confidence_score"],
                        name="words_user_id_268823_idx",
                    ),
                    models.Index(
                        fields=["user", "next_review_at"],
                        name="words_user_id_26ff03_idx",
                    ),
                    models.Index(
                        fields=["user", "category"], name="words_user_id_999b4e_idx"
                    ),
                ],
                "unique_together": {("user", "original_word")},
            },
        ),
    ]
