# Generated by Django 5.2.11 on 2026-02-07 06:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="easiness_factor",
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name="word",
            name="enriched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="word",
            name="enrichment_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="word",
            name="enrichment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("enriching", "Enriching"),
                    ("enriched", "Enriched"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="word",
            name="interval_days",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="word",
            name="mnemonic",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="word",
            name="repetition_number",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="word",
            name="usage_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.CreateModel(
            name="DailyStreak",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("current_streak", models.PositiveIntegerField(default=0)),
                ("longest_streak", models.PositiveIntegerField(default=0)),
                ("last_activity_date", models.DateField(blank=True, null=True)),
                ("streak_frozen_until", models.DateField(blank=True, null=True)),
                ("total_review_days", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streak",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Streak",
                "verbose_name_plural": "Daily Streaks",
                "db_table": "daily_streaks",
            },
        ),
        migrations.CreateModel(
            name="ReviewSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("total_words", models.PositiveIntegerField(default=0)),
                ("correct_count", models.PositiveIntegerField(default=0)),
                ("incorrect_count", models.PositiveIntegerField(default=0)),
                ("average_quality", models.FloatField(default=0.0)),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("review", "Review"),
                            ("quick", "Quick"),
                            ("focus", "Focus"),
                        ],
                        default="review",
                        max_length=10,
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Review Session",
                "verbose_name_plural": "Review Sessions",
                "db_table": "review_sessions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "quality",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "response_time_ms",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("is_correct", models.BooleanField()),
                ("reviewed_at", models.DateTimeField(auto_now_add=True)),
                ("previous_confidence", models.FloatField(default=0.0)),
                ("new_confidence", models.FloatField(default=0.0)),
                ("previous_interval", models.PositiveIntegerField(default=0)),
                ("new_interval", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_logs",
                        to="words.word",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="words.reviewsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review Log",
                "verbose_name_plural": "Review Logs",
                "db_table": "review_logs",
                "ordering": ["-reviewed_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("date", models.DateField()),
                ("words_reviewed", models.PositiveIntegerField(default=0)),
                ("words_added", models.PositiveIntegerField(default=0)),
                ("words_mastered", models.PositiveIntegerField(default=0)),
                ("correct_answers", models.PositiveIntegerField(default=0)),
                ("incorrect_answers", models.PositiveIntegerField(default=0)),
                ("total_time_seconds", models.PositiveIntegerField(default=0)),
                ("goal_completed", models.BooleanField(default=False)),
                ("xp_earned", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Activity",
                "verbose_name_plural": "Daily Activities",
                "db_table": "daily_activities",
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
    ]
