# Generated by Django 5.2.11 on 2026-02-10 16:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0004_chatsession_chatmessage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesession",
            name="combo_xp_bonus",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="gamesession",
            name="current_combo",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="gamesession",
            name="max_combo",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="reviewsession",
            name="combo_xp_bonus",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="reviewsession",
            name="current_combo",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="reviewsession",
            name="max_combo",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="testsession",
            name="combo_xp_bonus",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="testsession",
            name="current_combo",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="testsession",
            name="max_combo",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="ConfusingPair",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("confusion_count", models.PositiveIntegerField(default=1)),
                ("last_confused_at", models.DateTimeField(auto_now=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("drill_data", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confusing_pairs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "word_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confused_as_first",
                        to="words.word",
                    ),
                ),
                (
                    "word_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confused_as_second",
                        to="words.word",
                    ),
                ),
            ],
            options={
                "verbose_name": "Confusing Pair",
                "verbose_name_plural": "Confusing Pairs",
                "db_table": "confusing_pairs",
                "ordering": ["-confusion_count", "-last_confused_at"],
                "unique_together": {("user", "word_1", "word_2")},
            },
        ),
        migrations.CreateModel(
            name="DailyChallenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("date", models.DateField()),
                ("challenges", models.JSONField(default=list)),
                ("all_completed", models.BooleanField(default=False)),
                ("bonus_claimed", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_challenges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Challenge",
                "verbose_name_plural": "Daily Challenges",
                "db_table": "daily_challenges",
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="WordDistractor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("distractors", models.JSONField(default=list)),
                ("language", models.CharField(default="uz", max_length=10)),
                (
                    "generated_by",
                    models.CharField(
                        choices=[("ai", "AI"), ("fallback", "Fallback")],
                        default="ai",
                        max_length=10,
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distractors",
                        to="words.word",
                    ),
                ),
            ],
            options={
                "verbose_name": "Word Distractor",
                "verbose_name_plural": "Word Distractors",
                "db_table": "word_distractors",
                "unique_together": {("word", "language")},
            },
        ),
    ]
