# Generated by Django 5.2.11 on 2026-02-12 16:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0005_gamesession_combo_xp_bonus_gamesession_current_combo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamesession",
            name="game_type",
            field=models.CharField(
                choices=[
                    ("speed_round", "Speed Round"),
                    ("word_match", "Word Match"),
                    ("word_context", "Word Context"),
                    ("story_builder", "Story Builder"),
                    ("listening_challenge", "Listening Challenge"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ListeningRound",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("round_number", models.PositiveIntegerField()),
                ("correct_answer", models.CharField(max_length=100)),
                ("user_answers", models.JSONField(default=list)),
                ("attempts_used", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=3)),
                ("is_correct", models.BooleanField(default=False)),
                ("hints_shown", models.JSONField(default=list)),
                ("score", models.PositiveIntegerField(default=0)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listening_rounds",
                        to="words.gamesession",
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="words.word"
                    ),
                ),
            ],
            options={
                "verbose_name": "Listening Round",
                "verbose_name_plural": "Listening Rounds",
                "db_table": "listening_rounds",
                "ordering": ["round_number"],
                "unique_together": {("session", "round_number")},
            },
        ),
        migrations.CreateModel(
            name="StoryRound",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("round_number", models.PositiveIntegerField()),
                ("ai_text", models.TextField()),
                ("user_text", models.TextField(blank=True, default="")),
                ("target_words", models.JSONField(default=list)),
                ("words_used", models.JSONField(default=list)),
                ("grammar_corrections", models.JSONField(default=list)),
                ("is_correct_usage", models.BooleanField(default=False)),
                ("score", models.PositiveIntegerField(default=0)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_rounds",
                        to="words.gamesession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Story Round",
                "verbose_name_plural": "Story Rounds",
                "db_table": "story_rounds",
                "ordering": ["round_number"],
                "unique_together": {("session", "round_number")},
            },
        ),
    ]
