# Generated by Django 5.2.11 on 2026-02-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0006_alter_gamesession_game_type_listeninground_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewsession",
            name="session_type",
            field=models.CharField(
                choices=[
                    ("review", "Review"),
                    ("quick", "Quick"),
                    ("focus", "Focus"),
                    ("learn", "Learn"),
                    ("mixed", "Mixed"),
                ],
                default="review",
                max_length=10,
            ),
        ),
    ]
