# Generated by Django 5.2.11 on 2026-02-22 14:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0007_alter_reviewsession_session_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamesession",
            name="game_type",
            field=models.CharField(
                choices=[
                    ("speed_round", "Speed Round"),
                    ("word_match", "Word Match"),
                    ("word_context", "Word Context"),
                    ("story_builder", "Story Builder"),
                    ("listening_challenge", "Listening Challenge"),
                    ("synonym_antonym", "Synonym & Antonym"),
                    ("irregular_verbs", "Irregular Verbs"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="IrregularVerbRound",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("round_number", models.PositiveIntegerField()),
                ("infinitive", models.CharField(max_length=50)),
                ("translation", models.CharField(default="", max_length=100)),
                ("correct_past_simple", models.CharField(max_length=50)),
                ("correct_past_participle", models.CharField(max_length=50)),
                (
                    "user_past_simple",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "user_past_participle",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("past_simple_correct", models.BooleanField(blank=True, null=True)),
                ("past_participle_correct", models.BooleanField(blank=True, null=True)),
                ("attempts_used", models.PositiveIntegerField(default=0)),
                ("hints_shown", models.JSONField(default=dict)),
                ("score", models.PositiveIntegerField(default=0)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="irregular_verb_rounds",
                        to="words.gamesession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Irregular Verb Round",
                "verbose_name_plural": "Irregular Verb Rounds",
                "db_table": "irregular_verb_rounds",
                "ordering": ["round_number"],
                "unique_together": {("session", "round_number")},
            },
        ),
        migrations.CreateModel(
            name="SynonymAntonymRound",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("round_number", models.PositiveIntegerField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[("synonym", "Synonym"), ("antonym", "Antonym")],
                        max_length=10,
                    ),
                ),
                ("word_text", models.CharField(default="", max_length=100)),
                ("correct_answer", models.CharField(max_length=100)),
                ("options", models.JSONField(default=list)),
                (
                    "user_answer",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("is_correct", models.BooleanField(blank=True, null=True)),
                ("score", models.PositiveIntegerField(default=0)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="synonym_antonym_rounds",
                        to="words.gamesession",
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="words.word",
                    ),
                ),
            ],
            options={
                "verbose_name": "Synonym Antonym Round",
                "verbose_name_plural": "Synonym Antonym Rounds",
                "db_table": "synonym_antonym_rounds",
                "ordering": ["round_number"],
                "unique_together": {("session", "round_number")},
            },
        ),
    ]
