# Generated by Django 5.2.11 on 2026-02-23 05:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0008_alter_gamesession_game_type_irregularverbround_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="word",
            name="is_archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name="word",
            index=models.Index(
                fields=["user", "is_archived"], name="words_user_id_76c346_idx"
            ),
        ),
    ]
