"""
Text cleaner module for smart import.

Cleans raw imported text by removing OCR noise, metadata, headers,
instructions, branding, and other non-vocabulary content.
"""

import re

# Branding / OCR noise words — lines containing these are removed
NOISE_WORDS = {
    "notebooklm", "notebook", "gner", "bonmo", "tlae", "goge",
    "reroers", "gerdscc", "dwoented", "pelton", "wilk",
    "saodwich", "personel", "antions", "streetr", "lonson",
    "ste", "com", "www",
}

# Branding line patterns — full line is removed if matched
BRANDING_LINE_PATTERNS = [
    r"(?i)powered\s+by\b",
    r"(?i)generated\s+by\b",
    r"(?i)created\s+(by|with)\b",
    r"(?i)made\s+with\b",
    r"(?i)\bchatgpt\b",
    r"(?i)\bopenai\b",
    r"(?i)\bnotebooklm\b",
    r"(?i)\bgoogle\s+ai\b",
    r"(?i)©\s*\d{4}",
    r"(?i)all\s+rights\s+reserved",
    r"(?i)^sources?$",
]

# Action/instruction line patterns — full line is removed
ACTION_LINE_PATTERNS = [
    r"(?i)click\s+here",
    r"(?i)tap\s+to\b",
    r"(?i)download\s+(pdf|file)",
    r"(?i)share\s+with\s+friends",
    r"(?i)subscribe\b",
    r"(?i)follow\s+us\b",
    r"(?i)sign\s+up\b",
    r"(?i)log\s*in\b",
]

# Instructional / motivational phrases to remove
INSTRUCTION_PATTERNS = [
    r"how\s+to\s+use",
    r"the\s+method",
    r"\bread\b.*\bvisualize\b",
    r"\bvisualize\b.*\bconnect\b",
    r"image\s+context",
    r"great\s+job",
    r"keep\s+practicing",
    r"try\s+to\s+use",
    r"review\s+challenge",
    r"source\s+material\s+adapted",
    r"designed\s+for",
    r"reading\s+starter",
    r"key\s+words?\s+(&|and)?\s*phrases",
    r"for\s+a2\+?\s+learners",
    r"essential\s+english\s+vocabulary",
    r"^\d+\s+key\s+words",
]

# Metadata patterns (full line removal)
METADATA_LINE_PATTERNS = [
    r"^date\s*:\s*\d",
    r"^time\s*:\s*\d",
    r"^\d{1,2}/\d{1,2}/\d{2,4}$",
    r"^\d{1,2}:\d{2}\s*(am|pm)$",
]


def clean_imported_text(raw_text: str) -> str:
    """
    Clean imported text by removing noise, metadata, instructions, etc.

    Steps:
    1. Remove URLs and emails
    2. Remove money values and pure-number lines
    3. Remove branding/noise words
    4. Remove instruction/meta lines
    5. Remove short meaningless lines
    6. Normalize blank lines
    """
    if not raw_text or not raw_text.strip():
        return ""

    lines = raw_text.split("\n")
    cleaned_lines = []

    for line in lines:
        stripped = line.strip()

        # Skip empty lines (will normalize later)
        if not stripped:
            cleaned_lines.append("")
            continue

        # STEP 1: Remove URLs and emails
        stripped = re.sub(r'https?://\S+|www\.\S+|\S+@\S+\.\S+', '', stripped).strip()
        if not stripped:
            continue

        # STEP 2: Remove money values and numeric metadata
        stripped = re.sub(r'\$[\d,.]+', '', stripped).strip()
        stripped = re.sub(r'\b\d+\.\d+m\b', '', stripped).strip()
        if not stripped:
            continue

        # Pure number lines
        if re.match(r'^[\d\s/:.,-]+$', stripped):
            continue

        # Metadata lines (Date: ..., Time: ...)
        is_metadata = False
        for pattern in METADATA_LINE_PATTERNS:
            if re.match(pattern, stripped, re.IGNORECASE):
                is_metadata = True
                break
        if is_metadata:
            continue

        # STEP 3: Branding / noise words
        lower = stripped.lower()
        is_noise = False
        for noise in NOISE_WORDS:
            if lower == noise or lower.replace(" ", "") == noise:
                is_noise = True
                break
        if is_noise:
            continue

        # Short lines (1-2 words) with noise words
        words_in_line = lower.split()
        if len(words_in_line) <= 2:
            if any(w in NOISE_WORDS for w in words_in_line):
                continue

        # Branding line patterns ("Powered by NotebookLM", "Generated by ChatGPT")
        is_branding = False
        for pattern in BRANDING_LINE_PATTERNS:
            if re.search(pattern, stripped):
                is_branding = True
                break
        if is_branding:
            continue

        # Action/instruction line patterns ("Click here to", "Tap to listen")
        is_action = False
        for pattern in ACTION_LINE_PATTERNS:
            if re.search(pattern, stripped):
                is_action = True
                break
        if is_action:
            continue

        # STEP 4: Instruction / meta lines
        is_instruction = False
        for pattern in INSTRUCTION_PATTERNS:
            if re.search(pattern, lower):
                is_instruction = True
                break
        if is_instruction:
            continue

        # STEP 5: Short meaningless lines
        # 1-2 character lines (DE, CA, PM, ab, xy, etc.)
        if len(stripped) <= 2:
            continue
        # Lines of only special chars
        if re.match(r'^[^\w\s]+$', stripped):
            continue
        # Lines of only dots, commas, dashes
        if re.match(r'^[.,\-–—_=+*#]+$', stripped):
            continue

        cleaned_lines.append(stripped)

    # STEP 6: Normalize blank lines
    result_lines = []
    prev_blank = False
    for line in cleaned_lines:
        if not line:
            if not prev_blank:
                result_lines.append("")
            prev_blank = True
        else:
            result_lines.append(line)
            prev_blank = False

    # Strip leading/trailing blanks
    text = "\n".join(result_lines).strip()
    return text


def extract_document_sections(cleaned_text: str) -> list[dict]:
    """
    Split cleaned text into sections based on Unit/Chapter headers.

    Returns list of dicts:
    [
        {
            "title": "Unit 9: The Anatomy of a Kangaroo",
            "lines": ["1. Female", "Urg'ochi", ...]
        },
        ...
    ]
    """
    if not cleaned_text or not cleaned_text.strip():
        return []

    lines = cleaned_text.split("\n")
    sections = []
    current_section = None

    # Section header patterns
    section_patterns = [
        r"^unit\s+\d+",
        r"^chapter\s+\d+",
        r"^section\s+\d+",
        r"^lesson\s+\d+",
        r"^part\s+\d+",
        r"^topic\s+\d+",
        r"^###\s+",
        r"^\*\*[^*]+\*\*$",
    ]

    for line in lines:
        stripped = line.strip()
        if not stripped:
            if current_section:
                current_section["lines"].append("")
            continue

        # Check if this is a section header
        is_header = False
        for pattern in section_patterns:
            if re.match(pattern, stripped, re.IGNORECASE):
                is_header = True
                break

        # Also check: ALL CAPS line with 3+ words
        if not is_header and stripped.isupper() and len(stripped.split()) >= 3:
            is_header = True

        if is_header:
            current_section = {"title": stripped, "lines": []}
            sections.append(current_section)
        else:
            if current_section is None:
                current_section = {"title": "", "lines": []}
                sections.append(current_section)
            current_section["lines"].append(stripped)

    # Clean up empty trailing lines in sections
    for section in sections:
        while section["lines"] and not section["lines"][-1]:
            section["lines"].pop()

    return sections if sections else [{"title": "", "lines": lines}]
