"""
Tests for Smart Import helpers (Sprint 12.2).

Coverage: text_cleaner, language_detector, pair_extractor, translation_db.
Also: integration test for full AnalyzeTextUseCase pipeline.
"""

import pytest
from unittest.mock import MagicMock

from apps.words.application.use_cases.import_helpers.text_cleaner import (
    clean_imported_text,
    extract_document_sections,
)
from apps.words.application.use_cases.import_helpers.language_detector import (
    is_uzbek_word,
    is_english_word,
    has_uzbek_characters,
    is_document_title,
    classify_line,
)
from apps.words.application.use_cases.import_helpers.pair_extractor import (
    extract_word_pairs,
)
from apps.words.application.use_cases.import_helpers.translation_db import (
    COMMON_TRANSLATIONS,
    get_translation,
    estimate_cefr,
    CEFR_ORDER,
)


# ═══════════════════════════════════════════════════════════════════
# TEST TEXT CLEANER
# ═══════════════════════════════════════════════════════════════════


class TestTextCleaner:
    """Tests for text_cleaner module."""

    def test_removes_urls(self):
        text = "Learn at http://example.com or https://foo.bar/baz"
        result = clean_imported_text(text)
        assert "http" not in result
        assert "example.com" not in result

    def test_removes_money_patterns(self):
        text = "Price: $49.99 or 100 000 so'm"
        result = clean_imported_text(text)
        assert "$49.99" not in result

    def test_removes_branding(self):
        text = "Powered by NotebookLM\nGenerated by ChatGPT\nHello world"
        result = clean_imported_text(text)
        assert "NotebookLM" not in result
        assert "ChatGPT" not in result
        assert "Hello world" in result

    def test_removes_instruction_lines(self):
        text = "Click here to download\nTap to listen\nApple – olma"
        result = clean_imported_text(text)
        assert "Click here" not in result
        assert "Tap to listen" not in result
        assert "Apple" in result

    def test_removes_short_garbage(self):
        text = "ab\nxy\nHello – salom\nk"
        result = clean_imported_text(text)
        assert "ab" not in result.split("\n")[0] if result.strip() else True
        assert "Hello" in result

    def test_normalizes_blank_lines(self):
        text = "Line 1\n\n\n\n\nLine 2"
        result = clean_imported_text(text)
        # Should not have 5 blank lines
        assert "\n\n\n" not in result

    def test_preserves_valid_content(self):
        text = "1. Clap – qarsak chalmoq\n2. Smile – jilmaymoq"
        result = clean_imported_text(text)
        assert "Clap" in result
        assert "Smile" in result

    def test_extract_sections(self):
        text = """Unit 6: Our Favorite Hobbies
1. Clap – qarsak chalmoq

Unit 7: Animals
2. Kangaroo – kenguru"""
        sections = extract_document_sections(text)
        assert len(sections) >= 2
        assert "Unit 6" in sections[0]["title"] or "Unit 7" in sections[1]["title"]

    def test_real_pdf_noise_removal(self):
        """Simulate real PDF import noise."""
        noisy_text = """Sources
https://example.com/vocab-list.pdf

Fly English — Beginner Vocabulary

Unit 9: Health and Body
Share with friends · Download PDF

1. Headache – bosh og'rig'i
2. Medicine – dori
3. Fever – isitma

Generated by NotebookLM
© 2024 All Rights Reserved"""
        result = clean_imported_text(noisy_text)
        assert "https://" not in result
        assert "NotebookLM" not in result
        assert "© 2024" not in result or "All Rights Reserved" not in result
        assert "Headache" in result
        assert "Medicine" in result
        assert "Fever" in result


# ═══════════════════════════════════════════════════════════════════
# TEST LANGUAGE DETECTOR
# ═══════════════════════════════════════════════════════════════════


class TestLanguageDetector:
    """Tests for language_detector module."""

    def test_uzbek_common_words(self):
        assert is_uzbek_word("maqsad") is True
        assert is_uzbek_word("oziq") is True
        assert is_uzbek_word("qilmoq") is True
        assert is_uzbek_word("bo'lmoq") is True

    def test_uzbek_suffixes(self):
        assert is_uzbek_word("yozmoq") is True
        assert is_uzbek_word("ishlamoq") is True

    def test_uzbek_characters(self):
        assert has_uzbek_characters("o'qituvchi") is True
        assert has_uzbek_characters("g'alati") is True

    def test_english_words(self):
        assert is_english_word("headache") is True
        assert is_english_word("medicine") is True
        assert is_english_word("kangaroo") is True
        assert is_english_word("adventure") is True

    def test_not_english_uzbek(self):
        assert is_english_word("qilmoq") is False
        assert is_english_word("bo'lmoq") is False

    def test_not_english_noise(self):
        assert is_english_word("ab") is False  # too short (min 3 chars)
        assert is_english_word("xyz") is False  # no vowel
        assert is_english_word("bbb") is False  # no vowel

    def test_document_title(self):
        assert is_document_title("Unit 6: Our Favorite Hobbies") is True
        assert is_document_title("Chapter 3: Animals") is True
        assert is_document_title("clap – qarsak") is False

    def test_classify_line_header(self):
        result = classify_line("Unit 9: Health and Body")
        assert result in ("header", "title", "section_header")

    def test_classify_line_pair(self):
        result = classify_line("1. Headache – bosh og’rig’i")
        assert result in ("word_pair", "numbered_pair", "numbered_entry")

    def test_classify_line_noise(self):
        result = classify_line("https://example.com")
        assert result in ("noise", "url", "metadata", "unknown")


# ═══════════════════════════════════════════════════════════════════
# TEST PAIR EXTRACTOR
# ═══════════════════════════════════════════════════════════════════


class TestPairExtractor:
    """Tests for pair_extractor module."""

    def test_numbered_pairs(self):
        text = """1. Headache – bosh og'rig'i
2. Medicine – dori
3. Fever – isitma"""
        pairs = extract_word_pairs(text)
        assert len(pairs) >= 3
        words = [p["word"].lower() for p in pairs]
        assert "headache" in words
        assert "medicine" in words
        assert "fever" in words

    def test_dash_pairs(self):
        text = """Clap – qarsak chalmoq
Smile – jilmaymoq
Kick – tepmoq"""
        pairs = extract_word_pairs(text)
        assert len(pairs) >= 3
        words = [p["word"].lower() for p in pairs]
        assert "clap" in words
        assert "smile" in words

    def test_multi_unit_text(self):
        text = """Unit 6: Our Favorite Hobbies
1. Clap – qarsak chalmoq
2. Choose – tanlamoq

Unit 7: Animals and Nature
3. Kangaroo – kenguru
4. Dolphin – delfin"""
        pairs = extract_word_pairs(text)
        assert len(pairs) >= 4
        words = [p["word"].lower() for p in pairs]
        assert "clap" in words
        assert "kangaroo" in words

    def test_confidence_scores(self):
        text = "1. Headache – bosh og'rig'i"
        pairs = extract_word_pairs(text)
        assert len(pairs) >= 1
        assert "confidence" in pairs[0]
        assert pairs[0]["confidence"] >= 0.8

    def test_deduplication(self):
        text = """1. Clap – qarsak chalmoq
2. Clap – qarsak
Clap – qarsak chalmoq"""
        pairs = extract_word_pairs(text)
        clap_count = sum(1 for p in pairs if p["word"].lower() == "clap")
        assert clap_count == 1

    def test_filters_noise(self):
        """OCR noise and Uzbek words should be filtered out."""
        text = """1. Headache – bosh og'rig'i
bonmo – tlae
maqsad – goal
2. Medicine – dori"""
        pairs = extract_word_pairs(text)
        words_lower = [p["word"].lower() for p in pairs]
        assert "headache" in words_lower
        assert "medicine" in words_lower
        # "bonmo" is noise, "maqsad" is Uzbek — should be filtered
        assert "bonmo" not in words_lower
        assert "maqsad" not in words_lower

    def test_empty_text(self):
        assert extract_word_pairs("") == []
        assert extract_word_pairs("   ") == []

    def test_no_pairs_in_plain_text(self):
        """Plain English text without dash pairs → returns few or no pairs."""
        text = "The quick brown fox jumps over the lazy dog."
        pairs = extract_word_pairs(text)
        # Should not extract random words as pairs
        assert len(pairs) <= 2


# ═══════════════════════════════════════════════════════════════════
# TEST TRANSLATION DB
# ═══════════════════════════════════════════════════════════════════


class TestTranslationDB:
    """Tests for translation_db module."""

    def test_common_translations_not_empty(self):
        assert len(COMMON_TRANSLATIONS) > 100

    def test_get_translation_known(self):
        # Translation DB may capitalize first letter
        assert get_translation("headache").lower() == "bosh og'rig'i"
        assert get_translation("medicine").lower() == "dori"
        assert get_translation("clap").lower() == "qarsak chalmoq"

    def test_get_translation_case_insensitive(self):
        assert get_translation("Headache").lower() == "bosh og'rig'i"
        assert get_translation("CLAP").lower() == "qarsak chalmoq"

    def test_get_translation_unknown(self):
        assert get_translation("supercalifragilistic") is None

    def test_estimate_cefr_short_word(self):
        level = estimate_cefr("cat")
        assert level in ("A1", "A2")

    def test_estimate_cefr_medium_word(self):
        level = estimate_cefr("adventure")
        assert level in ("B1", "B2", "A2")

    def test_estimate_cefr_long_word(self):
        level = estimate_cefr("sophisticated")
        assert level in ("C1", "C2")

    def test_cefr_order_values(self):
        assert CEFR_ORDER["A1"] > CEFR_ORDER["C2"]
        assert CEFR_ORDER["A2"] > CEFR_ORDER["B1"]


# ═══════════════════════════════════════════════════════════════════
# INTEGRATION TEST: FULL PIPELINE
# ═══════════════════════════════════════════════════════════════════


class TestSmartImportIntegration:
    """Integration tests for the full smart import pipeline."""

    def test_full_pdf_text_pipeline(self):
        """Simulate real PDF text import — clean → extract → enrich."""

        pdf_text = """Sources
https://example.com/vocab.pdf

Fly English — Beginner Vocabulary

Unit 9: Health and Body
Share with friends

1. Headache – bosh og'rig'i
2. Medicine – dori
3. Fever – isitma
4. Cough – yo'tal
5. Sneeze – aksirmoq

Unit 10: Food and Kitchen
6. Recipe – retsept
7. Delicious – mazali
8. Ingredient – tarkibiy qism
9. Dessert – desert
10. Slice – tilim

Unit 11: Travel
11. Adventure – sarguzasht
12. Passenger – yo'lovchi
13. Luggage – yuk
14. Departure – jo'nash
15. Destination – manzil

Generated by NotebookLM
© 2024"""

        # Step 1: Clean
        cleaned = clean_imported_text(pdf_text)
        assert "NotebookLM" not in cleaned
        assert "https://" not in cleaned
        assert "Headache" in cleaned
        assert "Adventure" in cleaned

        # Step 2: Extract pairs
        pairs = extract_word_pairs(cleaned)
        assert len(pairs) >= 15, f"Expected 15+ pairs, got {len(pairs)}"

        words = [p["word"].lower() for p in pairs]
        assert "headache" in words
        assert "medicine" in words
        assert "adventure" in words
        assert "destination" in words

        # Check no noise words
        for noise in ["notebooklm", "https", "sources", "share", "download"]:
            assert noise not in words, f"Noise word '{noise}' should not be extracted"

        # Step 3: Translation lookup
        for pair in pairs:
            word = pair["word"].lower()
            trans = get_translation(word)
            if trans:
                assert len(trans) > 0

    def test_pipeline_with_mock_use_case(self):
        """Test AnalyzeTextUseCase with mocked repos, no AI."""
        from apps.words.application.use_cases.smart_import import AnalyzeTextUseCase

        mock_word_repo = MagicMock()
        mock_word_repo.get_all_by_user.return_value = ([], 0)

        use_case = AnalyzeTextUseCase(
            word_repo=mock_word_repo,
            ai_provider=None,
            user_repo=None,
            prompt_template="",
            language_map={"uz": "Uzbek"},
        )

        text = """Unit 9: Health
1. Headache – bosh og'rig'i
2. Medicine – dori
3. Fever – isitma"""

        result = use_case.execute(
            user_id="00000000-0000-0000-0000-000000000001",
            text=text,
        )

        assert "suggestions" in result
        assert result["total_found"] >= 3
        words = [s["word"].lower() for s in result["suggestions"]]
        assert "headache" in words
        assert "medicine" in words
        assert "fever" in words

    def test_pipeline_with_ai_enrichment(self):
        """Test AnalyzeTextUseCase calling AI for enrichment."""
        from apps.words.application.use_cases.smart_import import AnalyzeTextUseCase

        mock_word_repo = MagicMock()
        mock_word_repo.get_all_by_user.return_value = ([], 0)

        mock_ai = MagicMock()
        mock_ai.generate_json.return_value = [
            {
                "word": "headache",
                "pronunciation": "/ˈhɛdˌeɪk/",
                "definition": "a pain in your head",
                "example": "I have a headache.",
                "part_of_speech": "noun",
                "cefr": "A2",
                "translation": "bosh og'rig'i",
            },
            {
                "word": "medicine",
                "pronunciation": "/ˈmɛdɪsɪn/",
                "definition": "a substance used to treat illness",
                "example": "Take your medicine.",
                "part_of_speech": "noun",
                "cefr": "A2",
                "translation": "dori",
            },
        ]

        use_case = AnalyzeTextUseCase(
            word_repo=mock_word_repo,
            ai_provider=mock_ai,
            user_repo=None,
            prompt_template="",
            language_map={"uz": "Uzbek"},
        )

        text = """1. Headache – bosh og'rig'i
2. Medicine – dori"""

        result = use_case.execute(
            user_id="00000000-0000-0000-0000-000000000001",
            text=text,
        )

        assert result["ai_used"] is True
        assert result["parse_mode"] == "ai"
        assert len(result["suggestions"]) >= 2

        headache = next(
            (s for s in result["suggestions"] if s["word"].lower() == "headache"),
            None,
        )
        assert headache is not None
        assert headache["pronunciation"] == "/ˈhɛdˌeɪk/"
        assert headache["definition"] != ""

    def test_pipeline_marks_library_words(self):
        """Words already in user library should be flagged."""
        from apps.words.application.use_cases.smart_import import AnalyzeTextUseCase

        # Mock existing word
        existing_word = MagicMock()
        existing_word.original_word = "headache"

        mock_word_repo = MagicMock()
        mock_word_repo.get_all_by_user.return_value = ([existing_word], 1)

        use_case = AnalyzeTextUseCase(
            word_repo=mock_word_repo,
            ai_provider=None,
            user_repo=None,
            prompt_template="",
            language_map={"uz": "Uzbek"},
        )

        text = """1. Headache – bosh og'rig'i
2. Medicine – dori"""

        result = use_case.execute(
            user_id="00000000-0000-0000-0000-000000000001",
            text=text,
        )

        headache = next(
            (s for s in result["suggestions"] if s["word"].lower() == "headache"),
            None,
        )
        medicine = next(
            (s for s in result["suggestions"] if s["word"].lower() == "medicine"),
            None,
        )

        assert headache is not None
        assert headache["in_user_library"] is True
        assert medicine is not None
        assert medicine["in_user_library"] is False
        assert result["already_in_library"] >= 1
        assert result["new_words"] >= 1

    def test_backward_compat_parse_structured_text(self):
        """Verify parse_structured_text still works as a standalone function."""
        from apps.words.application.use_cases.smart_import import parse_structured_text

        text = """Unit 6: Hobbies
1. Clap – qarsak chalmoq
2. Smile – jilmaymoq"""

        results = parse_structured_text(text)
        assert len(results) >= 2
        assert results[0]["word"] == "Clap"
        assert results[0]["translation"] == "qarsak chalmoq"

    def test_backward_compat_exports(self):
        """Verify backward-compatible exports from smart_import module."""
        from apps.words.application.use_cases.smart_import import (
            parse_structured_text,
            detect_structured_format,
            estimate_cefr,
            COMMON_TRANSLATIONS,
            CEFR_ORDER,
            STOP_WORDS,
        )
        assert callable(parse_structured_text)
        assert callable(detect_structured_format)
        assert callable(estimate_cefr)
        assert isinstance(COMMON_TRANSLATIONS, dict)
        assert isinstance(CEFR_ORDER, dict)
        assert isinstance(STOP_WORDS, set)
