"""
Irregular verbs data — used by the Irregular Verbs game.

Each entry: (infinitive, past_simple, past_participle, translation_uz)
Sorted by difficulty tiers (A1→C1).
"""

IRREGULAR_VERBS: list[tuple[str, str, str, str]] = [
    # ── A1 tier (very common) ─────────────────────────────────────
    ("be", "was/were", "been", "bo'lmoq"),
    ("have", "had", "had", "ega bo'lmoq"),
    ("do", "did", "done", "qilmoq"),
    ("go", "went", "gone", "bormoq"),
    ("say", "said", "said", "aytmoq"),
    ("get", "got", "got", "olmoq"),
    ("make", "made", "made", "yasmoq"),
    ("come", "came", "come", "kelmoq"),
    ("see", "saw", "seen", "ko'rmoq"),
    ("take", "took", "taken", "olmoq"),
    ("give", "gave", "given", "bermoq"),
    ("know", "knew", "known", "bilmoq"),
    ("think", "thought", "thought", "o'ylamoq"),
    ("tell", "told", "told", "aytmoq"),
    ("find", "found", "found", "topmoq"),
    ("put", "put", "put", "qo'ymoq"),
    ("read", "read", "read", "o'qimoq"),
    ("write", "wrote", "written", "yozmoq"),
    ("eat", "ate", "eaten", "yemoq"),
    ("drink", "drank", "drunk", "ichmoq"),

    # ── A2 tier ───────────────────────────────────────────────────
    ("buy", "bought", "bought", "sotib olmoq"),
    ("bring", "brought", "brought", "olib kelmoq"),
    ("begin", "began", "begun", "boshlamoq"),
    ("break", "broke", "broken", "sindirmoq"),
    ("build", "built", "built", "qurmoq"),
    ("catch", "caught", "caught", "tutmoq"),
    ("choose", "chose", "chosen", "tanlamoq"),
    ("cut", "cut", "cut", "kesmoq"),
    ("draw", "drew", "drawn", "chizmoq"),
    ("drive", "drove", "driven", "haydamoq"),
    ("fall", "fell", "fallen", "yiqilmoq"),
    ("feel", "felt", "felt", "his qilmoq"),
    ("fly", "flew", "flown", "uchmoq"),
    ("forget", "forgot", "forgotten", "unutmoq"),
    ("grow", "grew", "grown", "o'smoq"),
    ("hear", "heard", "heard", "eshitmoq"),
    ("hold", "held", "held", "ushlamoq"),
    ("keep", "kept", "kept", "saqlamoq"),
    ("leave", "left", "left", "tark etmoq"),
    ("let", "let", "let", "ruxsat bermoq"),
    ("lose", "lost", "lost", "yo'qotmoq"),
    ("meet", "met", "met", "uchrashmoq"),
    ("pay", "paid", "paid", "to'lamoq"),
    ("run", "ran", "run", "yugurmoq"),
    ("sell", "sold", "sold", "sotmoq"),
    ("send", "sent", "sent", "jo'natmoq"),
    ("sit", "sat", "sat", "o'tirmoq"),
    ("sleep", "slept", "slept", "uxlamoq"),
    ("speak", "spoke", "spoken", "gapirmoq"),
    ("spend", "spent", "spent", "sarflamoq"),
    ("stand", "stood", "stood", "turmoq"),
    ("swim", "swam", "swum", "suzmoq"),
    ("teach", "taught", "taught", "o'qitmoq"),
    ("understand", "understood", "understood", "tushunmoq"),
    ("wear", "wore", "worn", "kiymoq"),
    ("win", "won", "won", "yutmoq"),

    # ── B1 tier ───────────────────────────────────────────────────
    ("become", "became", "become", "bo'lmoq"),
    ("beat", "beat", "beaten", "urmoq"),
    ("bite", "bit", "bitten", "tishlamoq"),
    ("blow", "blew", "blown", "esmoq"),
    ("burn", "burnt", "burnt", "yonmoq"),
    ("cost", "cost", "cost", "turmoq (narx)"),
    ("deal", "dealt", "dealt", "shug'ullanmoq"),
    ("dig", "dug", "dug", "qazmoq"),
    ("feed", "fed", "fed", "boqmoq"),
    ("fight", "fought", "fought", "jang qilmoq"),
    ("freeze", "froze", "frozen", "muzlamoq"),
    ("hang", "hung", "hung", "osmoq"),
    ("hide", "hid", "hidden", "yashirmoq"),
    ("hit", "hit", "hit", "urmoq"),
    ("hurt", "hurt", "hurt", "og'ritmoq"),
    ("lay", "laid", "laid", "qo'ymoq"),
    ("lead", "led", "led", "boshqarmoq"),
    ("lend", "lent", "lent", "qarz bermoq"),
    ("lie", "lay", "lain", "yotmoq"),
    ("light", "lit", "lit", "yoqmoq"),
    ("mean", "meant", "meant", "anglatmoq"),
    ("prove", "proved", "proven", "isbotlamoq"),
    ("ride", "rode", "ridden", "minmoq"),
    ("ring", "rang", "rung", "jiringlamoq"),
    ("rise", "rose", "risen", "ko'tarilmoq"),
    ("shake", "shook", "shaken", "silkitmoq"),
    ("shine", "shone", "shone", "porlamoq"),
    ("shoot", "shot", "shot", "otmoq"),
    ("show", "showed", "shown", "ko'rsatmoq"),
    ("shut", "shut", "shut", "yopmoq"),
    ("sing", "sang", "sung", "qo'shiq aytmoq"),
    ("sink", "sank", "sunk", "cho'kmoq"),
    ("slide", "slid", "slid", "sirpanmoq"),
    ("steal", "stole", "stolen", "o'g'irlamoq"),
    ("stick", "stuck", "stuck", "yopishmoq"),
    ("strike", "struck", "struck", "urmoq"),
    ("swear", "swore", "sworn", "qasam ichmoq"),
    ("sweep", "swept", "swept", "supurmoq"),
    ("swing", "swung", "swung", "tebranmoq"),
    ("tear", "tore", "torn", "yirtmoq"),
    ("throw", "threw", "thrown", "tashlamoq"),
    ("wake", "woke", "woken", "uyg'onmoq"),

    # ── B2–C1 tier ────────────────────────────────────────────────
    ("arise", "arose", "arisen", "paydo bo'lmoq"),
    ("bend", "bent", "bent", "egmoq"),
    ("bet", "bet", "bet", "garov o'ynamoq"),
    ("bind", "bound", "bound", "bog'lamoq"),
    ("bleed", "bled", "bled", "qon oqmoq"),
    ("breed", "bred", "bred", "ko'paytirmoq"),
    ("burst", "burst", "burst", "portlamoq"),
    ("cast", "cast", "cast", "tashlamoq"),
    ("cling", "clung", "clung", "yopishmoq"),
    ("creep", "crept", "crept", "sudralmoq"),
    ("dare", "dared", "dared", "jur'at etmoq"),
    ("flee", "fled", "fled", "qochmoq"),
    ("forbid", "forbade", "forbidden", "taqiqlamoq"),
    ("forgive", "forgave", "forgiven", "kechimoq"),
    ("grind", "ground", "ground", "maydalmoq"),
    ("kneel", "knelt", "knelt", "tiz cho'kmoq"),
    ("lean", "leant", "leant", "suyanmoq"),
    ("leap", "leapt", "leapt", "sakramoq"),
    ("mistake", "mistook", "mistaken", "adashmoq"),
    ("overcome", "overcame", "overcome", "yengmoq"),
    ("quit", "quit", "quit", "tashlamoq"),
    ("sew", "sewed", "sewn", "tikmoq"),
    ("shed", "shed", "shed", "to'kmoq"),
    ("shrink", "shrank", "shrunk", "kichraymoq"),
    ("sow", "sowed", "sown", "ekmoq"),
    ("spill", "spilt", "spilt", "to'kib yubormoq"),
    ("spit", "spat", "spat", "tupurmoq"),
    ("spread", "spread", "spread", "tarqatmoq"),
    ("spring", "sprang", "sprung", "sakramoq"),
    ("sting", "stung", "stung", "chaqmoq"),
    ("stink", "stank", "stunk", "sasmoq"),
    ("strive", "strove", "striven", "harakat qilmoq"),
    ("undergo", "underwent", "undergone", "boshdan kechirmoq"),
    ("undertake", "undertook", "undertaken", "zimmasiga olmoq"),
    ("weave", "wove", "woven", "to'qimoq"),
    ("withdraw", "withdrew", "withdrawn", "chiqib ketmoq"),
    ("wring", "wrung", "wrung", "siqmoq"),
]


def get_verbs_by_tier(tier: str = "all") -> list[tuple[str, str, str, str]]:
    """Return verbs for a specific difficulty tier."""
    tiers = {
        "A1": IRREGULAR_VERBS[:20],
        "A2": IRREGULAR_VERBS[20:55],
        "B1": IRREGULAR_VERBS[55:97],
        "B2": IRREGULAR_VERBS[97:],
        "all": IRREGULAR_VERBS,
    }
    return tiers.get(tier, IRREGULAR_VERBS)
